USE [master]
GO
/****** Object:  Database [LAB1]    Script Date: 3/10/2021 09:19:53 ******/
CREATE DATABASE [LAB1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LAB1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS05\MSSQL\DATA\LAB1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LAB1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS05\MSSQL\DATA\LAB1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [LAB1] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LAB1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LAB1] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LAB1] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LAB1] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LAB1] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LAB1] SET ARITHABORT OFF 
GO
ALTER DATABASE [LAB1] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [LAB1] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LAB1] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LAB1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LAB1] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LAB1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LAB1] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LAB1] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LAB1] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LAB1] SET  ENABLE_BROKER 
GO
ALTER DATABASE [LAB1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LAB1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LAB1] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LAB1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LAB1] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LAB1] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LAB1] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LAB1] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LAB1] SET  MULTI_USER 
GO
ALTER DATABASE [LAB1] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LAB1] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LAB1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LAB1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LAB1] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LAB1] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [LAB1] SET QUERY_STORE = OFF
GO
USE [LAB1]
GO
/****** Object:  Table [dbo].[COURSE]    Script Date: 3/10/2021 09:19:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COURSE](
	[CID] [varchar](10) NULL,
	[CNAME] [varchar](30) NULL,
	[CREDIT] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ENROLLED]    Script Date: 3/10/2021 09:19:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ENROLLED](
	[SID] [varchar](10) NULL,
	[CID] [varchar](12) NULL,
	[DAY] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STUDENTS]    Script Date: 3/10/2021 09:19:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STUDENTS](
	[SID] [varchar](10) NULL,
	[SNAME] [varchar](30) NULL,
	[DOB] [varchar](50) NULL,
	[ADDRESS] [varchar](50) NULL,
	[ID_CARD] [varchar](12) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TABLENAME]    Script Date: 3/10/2021 09:19:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TABLENAME](
	[COLUMN1] [int] NOT NULL,
	[COLUMN2] [char](20) NULL,
	[COLUMN3] [varchar](20) NULL,
	[COLUMN4] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[COLUMN1] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [LAB1] SET  READ_WRITE 
GO
